version: '3.8'

services:
  frontend:
    build:
      context: ./carousel_frontend
      dockerfile: Dockerfile 
    image: frontend
    container_name: Fronend
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./carousel_backend
      dockerfile: Dockerfile 
    image: backend
    container_name: Backend
    restart: always

  ros_img:
    build:
      context: ./carousel_ros
      dockerfile: Dockerfile
    container_name: ROS
    user: root
    network_mode: host
    ipc: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./carousel_backend:/home/ubuntu/web/carousel_backend
    devices:
      - /dev/dri
    environment:
      ROS_MASTER_URI: http://localhost:11311
      QT_X11_NO_MITSHM: '1'
      DISPLAY: ${DISPLAY}
    privileged: true
    restart: always
    tty: true
