version: '3.3'

services:
  frontend:
    build:
      context: ./carousel_frontend
      dockerfile: Dockerfile 
    image: frontend
    container_name: Fronend
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./carousel_backend
      dockerfile: Dockerfile 
    depends_on:
      ros_img:
        condition: service_started
    ports:
      - "8000:8000"
    image: backend
    volumes:
      - ./carousel_backend:/home/ubuntu/web/carousel_backend
    container_name: Backend
    restart: always
    networks:
      - postgresql

  ros_img:
    build:
      context: ./carousel_ros
      dockerfile: Dockerfile
    container_name: ROS
    depends_on:
      postgresql:
        condition: service_started
    user: root
    network_mode: host
    ipc: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./carousel_backend:/home/ubuntu/web/carousel_backend
    devices:
      - /dev/dri
    environment:
      ROS_MASTER_URI: http://127.0.0.1:11311
      # ROS_IP: localhost
      QT_X11_NO_MITSHM: '1'
      DISPLAY: ${DISPLAY}
    ports:
     - 11311:11311
    privileged: true
    restart: always
    tty: true
    # networks:
    #   - postgresql

  # rabbit_mq:
  #   image: rabbitmq:3.13.6-management
  #   container_name: Rabbitmq
  #   hostname: rabbitmq
  #   restart: always
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=rmuser
  #     - RABBITMQ_DEFAULT_PASS=rmpassword
  #     - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
  #   volumes:
  #     - ./rabbitmq:/var/lib/rabbitmq
  #   ports:
  #     - 15672:15672
  #     - 5672:5672

  postgresql:
    image: postgres:14.13-bullseye
    container_name: Postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    restart: always
    environment:
      - POSTGRES_PASSWORD=Robot123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=carousel_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    networks:
      postgresql:
        ipv4_address: 10.5.0.5
    

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    user: "${UID}:${GID}"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pguser@habr.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpwd
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgresql

networks:
  postgresql:
    driver: bridge
    name: postgresql
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1